export default {
  BASE_SPACEX_URL: 'https://api.spacexdata.com/v3',

  // LAUNCH INDEX ACTIONS
  LAUNCHES_FETCH: 'LAUNCHES_FETCH',
  LAUNCHES_FETCH_SUCCESS: 'LAUNCHES_FETCH_SUCCESS',
  LAUNCHES_FETCH_ERROR: 'LAUNCHES_FETCH_ERROR',

  // LAUNCH
  LAUNCH_FETCH: 'LAUNCH_FETCH',
  LAUNCH_FETCH_SUCCESS: 'LAUNCH_FETCH_SUCCESS',
  LAUNCH_FETCH_ERROR: 'LAUNCH_FETCH_ERROR',
  LAUNCH_RESET: 'LAUNCH_RESET',
};
